# Generated by Django 5.2 on 2025-05-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiovideomedia',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='imagemedia',
            name='checksum',
        ),
        migrations.AlterField(
            model_name='audiovideomedia',
            name='encoded_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='audiovideomedia',
            name='status',
            field=models.CharField(choices=[('PENDING', 1), ('PROCESSING', 2), ('COMPLETED', 3), ('ERROR', 4)], default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.CharField(choices=[('ER', 1), ('L', 2), ('AGE_10', 3), ('AGE_12', 4), ('AGE_14', 5), ('AGE_16', 6), ('AGE_18', 7)], max_length=10),
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
